'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { join } = require('node:path');
const { createManagedProjectSnapshot } = require('../src/management/portfolio/index.cjs');
const { evaluateProjectAttention, scoreDecisionReplay } = require('../src/management/portfolio/attention-engine.cjs');

const corpus = JSON.parse(readFileSync(join(__dirname, '..', 'fixtures', 'management', 'm2-historical-controller-replay-v1.json'), 'utf8'));

test('M2 historical replay corpus is evidence-linked and manually labelled', () => {
  assert.equal(corpus.schema, 'aiexe.management-replay-corpus.v1');
  assert.match(corpus.labelPolicy, /not generated by the attention engine/);
  assert.ok(corpus.cases.length >= 5);
  for (const replay of corpus.cases) {
    assert.ok(replay.project.evidenceRefs.length >= 1);
    assert.ok(replay.labelEvidence.length >= 20);
    assert.ok(['continue', 'pause', 'escalate'].includes(replay.expectedType));
    assert.ok(['automatic', 'needs_attention', 'blocked'].includes(replay.expectedBucket));
  }
});

test('M2 deterministic engine reproduces the first evidence-linked historical corpus exactly', () => {
  const rows = [];
  for (const replay of corpus.cases) {
    const project = createManagedProjectSnapshot(replay.project);
    const packet = evaluateProjectAttention({
      portfolioId: 'group-portfolio',
      project,
      evaluatedAt: '2026-08-09T09:30:00Z',
    });
    assert.equal(packet.proposal.type, replay.expectedType, replay.id);
    assert.equal(packet.bucket, replay.expectedBucket, replay.id);
    rows.push({ expectedType: replay.expectedType, actualType: packet.proposal.type });
  }
  const score = scoreDecisionReplay(rows);
  assert.equal(score.total, corpus.cases.length);
  assert.equal(score.exactMatches, corpus.cases.length);
  assert.equal(score.exactRate, 1);
  assert.equal(score.falseEscalations, 0);
  assert.equal(score.missedEscalations, 0);
});
